Ttree:
  Fusion:
    DocumentFinder:
      documentPrototype:
        fallback: 'Ttree.LearnNeosCustomNode:DefaultPage'

Neos:
  Neos:
    fusion:
      autoInclude:
        Ttree.LearnNeosCustomNode: true

